[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

dependencies = [
    "mlflow",
    "hydra-core",
    "torch",
    "torchvision",
    "scikit-learn",
    "jupyterlab",
    "opencv-python",
    "captum",
    "protobuf",
]

[tool.uv]
package = false
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
